---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3tester
  namespace: namespace-core
data:
  AWS_DEFAULT_REGION: us-east-1
  AWS_STS_REGIONAL_ENDPOINTS: regional
  BUCKET_NAME: amp-prod-network-d32f22f
  REGION: us-east-1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: s3tester
  namespace: namespace-core
spec:
  template:
    spec:
      serviceAccountName: spans-s3-write-access
      containers:
      - name: s3tester
        image: nfinstana/s3tester:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: s3tester
      restartPolicy: Never
  backoffLimit: 4
